"""create users, bourses, users_bourses tables

Revision ID: 549eb8cbcda7
Revises: 9ec2186b0d55
Create Date: 2026-07-01 21:14:09.213034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549eb8cbcda7'
down_revision = '9ec2186b0d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bourses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('lien', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_bourses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bourse_id', sa.String(length=36), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bourse_id'], ['bourses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bourse_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_bourses')
    op.drop_table('bourses')
    # ### end Alembic commands ###
